# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/REIT4842_notes',
                'doc_host': 'https://bthek1.github.io',
                'git_url': 'https://github.com/bthek1/REIT4842_notes',
                'lib_path': 'REIT4842_notes'},
  'syms': {'REIT4842_notes.core': {'REIT4842_notes.core.foo': ('core.html#foo', 'REIT4842_notes/core.py')}}}
